import type { PluginDefinition } from '$lib/plugin-contracts';

const plugin: PluginDefinition = {
  meta: {
    id: 'permission-management',
    name: 'Permission management',
    description:
      'Manages users, administrator permissions, group-based API access, and detailed permission overrides.',
    version: '1.0.0',
    category: 'core',
    required: true,
    order: 30,
    adminAccessPermissions: ['manageUsers', 'managePermissions'],
  },
  translations: {
    ko: {
      meta: {
        name: '권한 관리',
        description:
          '사용자, 관리자 권한, 그룹 기반 API 및 세부 권한 override를 관리합니다.',
        category: 'core',
      },
      strings: {
        'admin.permissionGroups': '권한 그룹',
        'admin.permissionGroupsDescription':
          '사용자 또는 IP 대역을 그룹에 넣고 그룹별로 사이트 기본 권한을 override합니다.',
        'admin.groupName': '그룹 이름',
        'admin.description': '설명',
        'admin.addGroup': '그룹 추가',
        'admin.selectedCount': '{count}개 선택',
        'admin.deleteSelected': '선택 삭제',
        'admin.deleteSelectedGroupsTitle': '선택한 권한 그룹을 삭제할까요?',
        'admin.deleteSelectedGroupsMessage':
          '{count}개 권한 그룹과 해당 사용자/CIDR 할당이 삭제됩니다.',
        'admin.deleteSelectedGroupsConfirm': '선택 그룹 삭제',
        'admin.selectGroup': '{name} 선택',
        'admin.noDescription': '설명 없음',
        'admin.disabled': '비활성화됨',
        'admin.disabledSuffix': ' · 비활성',
        'admin.adminSuffix': ' · 관리자',
        'admin.priorityValue': '우선순위 {value}',
        'admin.groupAssignmentCounts': '사용자 {users} · CIDR {cidrs}',
        'admin.edit': '수정',
        'admin.emptyGroups': '아직 권한 그룹이 없습니다.',
        'admin.localUsers': '로컬 사용자',
        'admin.localUsersDescription':
          '관리자 권한과 계정 활성화 상태를 관리합니다.',
        'admin.userSearchPlaceholder': '이름, 이메일, ID 검색',
        'admin.search': '검색',
        'admin.reset': '초기화',
        'admin.emailPlaceholder': 'user@example.com',
        'admin.name': '이름',
        'admin.passwordPolicyFallback': '10자 이상 비밀번호',
        'admin.administrator': '관리자',
        'admin.addUser': '사용자 추가',
        'admin.emptyUsers': '사용자를 찾을 수 없습니다.',
        'admin.userPage': '사용자 페이지',
        'admin.userInformation': '사용자 정보',
        'admin.email': '이메일',
        'admin.newPassword': '새 비밀번호',
        'admin.changeOnlyPlaceholder': '변경할 때만 입력',
        'admin.enabled': '활성화',
        'admin.save': '저장',
        'admin.apiTokens': 'API 토큰',
        'admin.apiTokensDescription':
          '이 사용자에게 발급된 API 토큰을 확인하고 즉시 폐기합니다.',
        'admin.createdAt': '생성일',
        'admin.lastUsedAt': '마지막 사용',
        'admin.neverUsed': '사용 기록 없음',
        'admin.revokeApiToken': '토큰 폐기',
        'admin.revokeApiTokenTitle': 'API 토큰을 폐기할까요?',
        'admin.revokeApiTokenMessage':
          '이 토큰은 즉시 사용할 수 없게 됩니다. 이 작업은 되돌릴 수 없습니다.',
        'admin.revokeApiTokenConfirm': 'API 토큰 폐기',
        'admin.emptyApiTokens': '발급된 API 토큰이 없습니다.',
        'admin.dangerZone': '위험 작업',
        'admin.deleteUser': '사용자 삭제',
        'admin.deleteUserTitle': '사용자를 삭제할까요?',
        'admin.deleteUserMessage':
          '이 사용자의 계정 데이터와 생성한 링크가 삭제됩니다. 이 작업은 복구할 수 없습니다.',
        'admin.deleteUserConsent':
          '삭제되는 사용자 데이터와 생성 링크를 복구할 수 없다는 점을 이해했습니다.',
        'admin.priority': '우선순위',
        'admin.enableGroup': '그룹 활성화',
        'admin.automaticAssignment': '자동 사용자 할당',
        'admin.automaticAssignmentDescription':
          '조건을 만족하는 회원을 이 그룹에 자동으로 추가합니다.',
        'admin.enableAutomaticAssignment': '자동 할당 활성화',
        'admin.emailDomains': '이메일 도메인',
        'admin.emailDomainsHelp':
          '한 줄 또는 쉼표로 구분하세요. example.com은 하위 도메인도 포함합니다.',
        'admin.revokeWhenUnmatched': '조건 불일치 시 자동 회수',
        'admin.revokeWhenUnmatchedHelp':
          '조건을 더 이상 만족하지 않는 사용자의 자동 할당만 제거합니다. 수동 할당은 유지됩니다.',
        'admin.automaticAssignmentBadge': '자동 할당',
        'admin.manualAssignmentBadge': '수동 할당',
        'admin.permissionGroupSettings': '권한 그룹 설정',
        'admin.links': '링크',
        'admin.api': 'API',
        'admin.linkPermissions': '링크 권한',
        'admin.createLinks': '링크 생성',
        'admin.deleteOwnLinks': '본인 링크 삭제',
        'admin.editOwnLinks': '본인 링크 수정',
        'admin.viewOtherLinks': '다른 사용자 링크 보기',
        'admin.editOtherLinks': '다른 사용자 링크 수정',
        'admin.deleteOtherLinks': '다른 사용자 링크 삭제',
        'admin.viewOtherStats': '다른 사용자 링크 통계 보기',
        'admin.downloadStatsCsv': '통계 CSV 다운로드',
        'admin.checkOtherLinkHealth': '다른 사용자 링크 상태 확인',
        'admin.bypassExpiration': '만료일 우회',
        'admin.bypassPasswords': '비밀번호 우회',
        'admin.customCode': '커스텀 코드',
        'admin.previewTitle': '공유 제목',
        'admin.previewDescription': '공유 설명',
        'admin.previewImageUrl': '공유 이미지 URL',
        'admin.themeColor': '테마 컬러',
        'admin.utmSource': 'UTM source',
        'admin.utmMedium': 'UTM medium',
        'admin.utmCampaign': 'UTM campaign',
        'admin.utmTerm': 'UTM term',
        'admin.utmContent': 'UTM content',
        'admin.expirationDate': '만료일',
        'admin.maxClicks': '최대 클릭 수',
        'admin.password': '비밀번호',
        'admin.tags': '태그',
        'admin.mobileDestination': '모바일 목적지',
        'admin.desktopDestination': '데스크톱 목적지',
        'admin.abDestination': 'A/B 목적지',
        'admin.abPercentage': 'A/B 비율',
        'admin.destinationUrl': '목적지 URL',
        'admin.inheritDefault': '기본값 유지',
        'admin.allow': '허용',
        'admin.deny': '차단',
        'admin.override': 'override',
        'admin.linkCreationOptions': '링크 생성 옵션',
        'admin.linkEditingOptions': '링크 수정 옵션',
        'admin.codeAndDeletionConditions': '코드와 삭제 조건',
        'admin.minimumLength': '최소 길이',
        'admin.maximumLength': '최대 길이',
        'admin.generatedCodeLength': '생성 코드 길이',
        'admin.maxClicksForDeletion': '삭제 허용 최대 클릭 수',
        'admin.overrideCodeMinLength': '코드 최소 길이 override',
        'admin.overrideCodeMaxLength': '코드 최대 길이 override',
        'admin.overrideGeneratedCodeLength': '자동 코드 길이 override',
        'admin.overrideDeleteMaxClicks': '삭제 클릭 수 조건 override',
        'admin.zeroMeansUnlimited': '0은 무제한',
        'admin.adminAccess': '관리자 접근',
        'admin.adminPageAccess': '관리자 페이지 접근',
        'admin.userManagement': '사용자 관리',
        'admin.permissionGroupManagement': '권한 그룹 관리',
        'admin.accessiblePluginIds': '접근 가능한 플러그인 ID',
        'admin.accessiblePluginIdsHelp':
          '*는 모든 플러그인을 의미합니다. 줄바꿈 또는 쉼표로 구분하세요.',
        'admin.accessibleAdminTabs': '접근 가능한 관리자 탭',
        'admin.manageableAdminTabs': '관리 가능한 관리자 탭',
        'admin.siteSection': '사이트',
        'admin.linksAndApiSection': '링크 및 API',
        'admin.themeSection': '테마',
        'admin.pluginsSection': '플러그인',
        'admin.linkManagementSection': '링크 관리',
        'admin.apiPermissions': 'API 권한',
        'admin.apiAccess': 'API 사용',
        'admin.createLinksApi': '링크 생성 API',
        'admin.listApi': '목록 API',
        'admin.statsApi': '통계 API',
        'admin.deleteApi': '삭제 API',
        'admin.updateApi': '수정 API',
        'admin.savePermissionGroup': '권한 그룹 저장',
        'admin.cidrManagement': 'CIDR 관리',
        'admin.searchCidr': 'CIDR 검색',
        'admin.expirationDateTime': '만료일시',
        'admin.addCidr': 'CIDR 추가',
        'admin.registeredCidrs': '등록 CIDR',
        'admin.deleteSelectedCidrsTitle': '선택한 CIDR 규칙을 삭제할까요?',
        'admin.deleteSelectedCidrsMessage':
          '{count}개 CIDR 규칙이 이 그룹에서 제거됩니다.',
        'admin.deleteSelectedCidrsConfirm': '선택 CIDR 삭제',
        'admin.selectCidr': '{cidr} 선택',
        'admin.remove': '제거',
        'admin.emptyCidrSearch': '검색된 CIDR 규칙이 없습니다.',
        'admin.emptyRegisteredCidrs': '등록된 CIDR 규칙이 없습니다.',
        'admin.cidrManagementPage': 'CIDR 관리 페이지',
        'admin.groupUsers': '그룹 사용자',
        'admin.searchCurrentMembers': '현재 멤버 검색',
        'admin.searchMembers': '멤버 검색',
        'admin.searchUsersToAdd': '추가할 사용자 검색',
        'admin.searchUsers': '사용자 검색',
        'admin.currentMembers': '현재 멤버',
        'admin.selectedUsersCount': '{count}명 선택',
        'admin.deleteSelectedUsersTitle':
          '선택한 사용자를 그룹에서 삭제할까요?',
        'admin.deleteSelectedUsersMessage':
          '{count}명 사용자가 이 그룹에서 제거됩니다.',
        'admin.deleteSelectedUsersConfirm': '선택 사용자 삭제',
        'admin.selectUser': '{name} 선택',
        'admin.emptyGroupMembers': '그룹에 포함된 사용자가 없습니다.',
        'admin.groupMemberPage': '그룹 멤버 페이지',
        'admin.add': '추가',
        'admin.cancel': '취소',
        'admin.addUserToGroup': '그룹에 사용자 추가',
        'admin.addUserToGroupDescription':
          '{name} 사용자를 이 권한 그룹에 추가합니다.',
        'admin.assignmentReason': '사유',
        'admin.assignmentReasonPlaceholder':
          '사용자에게 이 권한 그룹을 적용하는 이유',
        'admin.assignmentReasonPublicCheckbox':
          '이 사유를 사용자와 API 응답에 공개',
        'admin.assignmentReasonPublic': '사유 공개',
        'admin.assignmentReasonPrivate': '사유 비공개',
        'admin.emptyAddableUsers': '추가할 수 있는 사용자가 없습니다.',
        'admin.searchUsersByNameEmailId':
          '이름, 이메일, ID로 사용자를 검색하세요.',
        'admin.addableUsersPage': '추가할 사용자 페이지',
        'admin.deleteGroup': '그룹 삭제',
        'admin.deleteGroupTitle': '권한 그룹을 삭제할까요?',
        'admin.deleteGroupMessage':
          '이 그룹에 설정된 모든 권한 override가 제거됩니다.',
        'admin.itemNotFound': '관리 항목을 찾을 수 없습니다.',
        'admin.noExpiration': '만료 없음',
        'admin.expirationDateError': '만료일 오류',
        'admin.expiredAt': '만료됨 {value}',
        'admin.expiresAt': '만료 {value}',
        'server.adminUserRequiresRoot':
          '관리자 사용자는 최상위 관리자만 만들거나 수정할 수 있습니다.',
        'server.adminUserManageRequiresRoot':
          '관리자 사용자는 최상위 관리자만 관리할 수 있습니다.',
        'server.manageUsersDenied': '사용자 관리 권한이 없습니다.',
        'server.permissionActionDenied':
          '이 권한 관리 작업을 수행할 권한이 없습니다.',
        'server.userCreated': '사용자를 추가했습니다.',
        'server.groupCreated': '권한 그룹을 추가했습니다.',
        'server.selectGroupsToDelete': '삭제할 권한 그룹을 선택해주세요.',
        'server.groupsDeleted': '{count}개 권한 그룹을 삭제했습니다.',
        'server.unsupportedPluginAction': '지원하지 않는 플러그인 작업입니다.',
        'server.userNotFound': '사용자를 찾을 수 없습니다.',
        'server.groupNotFound': '권한 그룹을 찾을 수 없습니다.',
        'server.invalidAdminItem': '관리 항목이 올바르지 않습니다.',
        'server.userSaved': '사용자 정보를 저장했습니다.',
        'server.userDeleted': '사용자를 삭제했습니다.',
        'server.groupSaved': '권한 그룹을 저장했습니다.',
        'server.groupUserAdded': '그룹에 사용자를 추가했습니다.',
        'server.groupUserRemoved': '그룹에서 사용자를 제거했습니다.',
        'server.selectUsersToRemove': '제거할 사용자를 선택해주세요.',
        'server.usersRemoved': '{count}명 사용자를 그룹에서 제거했습니다.',
        'server.groupCidrAdded': '그룹에 CIDR 규칙을 추가했습니다.',
        'server.groupCidrRemoved': '그룹에서 CIDR 규칙을 제거했습니다.',
        'server.selectCidrsToRemove': '제거할 CIDR 규칙을 선택해주세요.',
        'server.cidrsRemoved': '{count}개 CIDR 규칙을 그룹에서 제거했습니다.',
        'server.groupDeleted': '권한 그룹을 삭제했습니다.',
        'server.apiTokenNotFound': 'API 토큰을 찾을 수 없습니다.',
        'server.apiTokenRevoked': 'API 토큰을 폐기했습니다.',
        'server.unsupportedPermissionAction':
          '지원하지 않는 권한 관리 작업입니다.',
      },
    },
    en: {
      meta: {
        name: 'Permission management',
        description:
          'Manages users, administrator permissions, group-based API access, and detailed permission overrides.',
        category: 'core',
      },
      strings: {
        'admin.permissionGroups': 'Permission groups',
        'admin.permissionGroupsDescription':
          'Put users or IP ranges into groups and override site defaults per group.',
        'admin.groupName': 'Group name',
        'admin.description': 'Description',
        'admin.addGroup': 'Add group',
        'admin.selectedCount': '{count} selected',
        'admin.deleteSelected': 'Delete selected',
        'admin.deleteSelectedGroupsTitle': 'Delete selected permission groups?',
        'admin.deleteSelectedGroupsMessage':
          '{count} permission groups and their user/CIDR assignments will be deleted.',
        'admin.deleteSelectedGroupsConfirm': 'Delete selected groups',
        'admin.selectGroup': 'Select {name}',
        'admin.noDescription': 'No description',
        'admin.disabled': 'Disabled',
        'admin.disabledSuffix': ' · Disabled',
        'admin.adminSuffix': ' · Administrator',
        'admin.priorityValue': 'Priority {value}',
        'admin.groupAssignmentCounts': 'Users {users} · CIDRs {cidrs}',
        'admin.edit': 'Edit',
        'admin.emptyGroups': 'No permission groups yet.',
        'admin.localUsers': 'Local users',
        'admin.localUsersDescription':
          'Manage administrator status and account activation.',
        'admin.userSearchPlaceholder': 'Search name, email, or ID',
        'admin.search': 'Search',
        'admin.reset': 'Reset',
        'admin.emailPlaceholder': 'user@example.com',
        'admin.name': 'Name',
        'admin.passwordPolicyFallback': 'Password, at least 10 characters',
        'admin.administrator': 'Administrator',
        'admin.addUser': 'Add user',
        'admin.emptyUsers': 'No users found.',
        'admin.userPage': 'User page',
        'admin.userInformation': 'User information',
        'admin.email': 'Email',
        'admin.newPassword': 'New password',
        'admin.changeOnlyPlaceholder': 'Enter only when changing it',
        'admin.enabled': 'Enabled',
        'admin.save': 'Save',
        'admin.apiTokens': 'API tokens',
        'admin.apiTokensDescription':
          'Review and immediately revoke API tokens issued to this user.',
        'admin.createdAt': 'Created',
        'admin.lastUsedAt': 'Last used',
        'admin.neverUsed': 'Never used',
        'admin.revokeApiToken': 'Revoke token',
        'admin.revokeApiTokenTitle': 'Revoke API token?',
        'admin.revokeApiTokenMessage':
          'This token will stop working immediately. This cannot be undone.',
        'admin.revokeApiTokenConfirm': 'Revoke API token',
        'admin.emptyApiTokens': 'No API tokens have been issued.',
        'admin.dangerZone': 'Danger zone',
        'admin.deleteUser': 'Delete user',
        'admin.deleteUserTitle': 'Delete this user?',
        'admin.deleteUserMessage':
          'This user account data and created links will be deleted. This cannot be undone.',
        'admin.deleteUserConsent':
          'I understand that the deleted user data and created links cannot be recovered.',
        'admin.priority': 'Priority',
        'admin.enableGroup': 'Enable group',
        'admin.automaticAssignment': 'Automatic user assignment',
        'admin.automaticAssignmentDescription':
          'Automatically add members who satisfy the configured conditions to this group.',
        'admin.enableAutomaticAssignment': 'Enable automatic assignment',
        'admin.emailDomains': 'Email domains',
        'admin.emailDomainsHelp':
          'Separate by line or comma. example.com also includes subdomains.',
        'admin.revokeWhenUnmatched': 'Automatically revoke when unmatched',
        'admin.revokeWhenUnmatchedHelp':
          'Only automatic assignments are removed when a user no longer matches. Manual assignments stay intact.',
        'admin.automaticAssignmentBadge': 'Automatic assignment',
        'admin.manualAssignmentBadge': 'Manual assignment',
        'admin.permissionGroupSettings': 'Permission group settings',
        'admin.links': 'Links',
        'admin.api': 'API',
        'admin.linkPermissions': 'Link permissions',
        'admin.createLinks': 'Create links',
        'admin.deleteOwnLinks': 'Delete own links',
        'admin.editOwnLinks': 'Edit own links',
        'admin.viewOtherLinks': 'View other users links',
        'admin.editOtherLinks': 'Edit other users links',
        'admin.deleteOtherLinks': 'Delete other users links',
        'admin.viewOtherStats': 'View other users stats',
        'admin.downloadStatsCsv': 'Download stats CSV',
        'admin.checkOtherLinkHealth': 'Check other users link health',
        'admin.bypassExpiration': 'Bypass expiration',
        'admin.bypassPasswords': 'Bypass passwords',
        'admin.customCode': 'Custom code',
        'admin.previewTitle': 'Preview title',
        'admin.previewDescription': 'Preview description',
        'admin.previewImageUrl': 'Preview image URL',
        'admin.themeColor': 'Theme color',
        'admin.utmSource': 'UTM source',
        'admin.utmMedium': 'UTM medium',
        'admin.utmCampaign': 'UTM campaign',
        'admin.utmTerm': 'UTM term',
        'admin.utmContent': 'UTM content',
        'admin.expirationDate': 'Expiration date',
        'admin.maxClicks': 'Max clicks',
        'admin.password': 'Password',
        'admin.tags': 'Tags',
        'admin.mobileDestination': 'Mobile destination',
        'admin.desktopDestination': 'Desktop destination',
        'admin.abDestination': 'A/B destination',
        'admin.abPercentage': 'A/B percentage',
        'admin.destinationUrl': 'Destination URL',
        'admin.inheritDefault': 'Inherit default',
        'admin.allow': 'Allow',
        'admin.deny': 'Deny',
        'admin.override': 'Override',
        'admin.linkCreationOptions': 'Link creation options',
        'admin.linkEditingOptions': 'Link editing options',
        'admin.codeAndDeletionConditions': 'Code and deletion conditions',
        'admin.minimumLength': 'Minimum length',
        'admin.maximumLength': 'Maximum length',
        'admin.generatedCodeLength': 'Generated code length',
        'admin.maxClicksForDeletion': 'Max clicks allowed for deletion',
        'admin.overrideCodeMinLength': 'Override code minimum length',
        'admin.overrideCodeMaxLength': 'Override code maximum length',
        'admin.overrideGeneratedCodeLength': 'Override generated code length',
        'admin.overrideDeleteMaxClicks':
          'Override max clicks allowed for deletion',
        'admin.zeroMeansUnlimited': '0 means unlimited',
        'admin.adminAccess': 'Administrator access',
        'admin.adminPageAccess': 'Admin page access',
        'admin.userManagement': 'User management',
        'admin.permissionGroupManagement': 'Permission group management',
        'admin.accessiblePluginIds': 'Accessible plugin IDs',
        'admin.accessiblePluginIdsHelp':
          '* means all plugins. Separate by line or comma.',
        'admin.accessibleAdminTabs': 'Accessible admin tabs',
        'admin.manageableAdminTabs': 'Manageable admin tabs',
        'admin.siteSection': 'Site',
        'admin.linksAndApiSection': 'Links and API',
        'admin.themeSection': 'Theme',
        'admin.pluginsSection': 'Plugins',
        'admin.linkManagementSection': 'Link management',
        'admin.apiPermissions': 'API permissions',
        'admin.apiAccess': 'API access',
        'admin.createLinksApi': 'Create links API',
        'admin.listApi': 'List API',
        'admin.statsApi': 'Stats API',
        'admin.deleteApi': 'Delete API',
        'admin.updateApi': 'Update API',
        'admin.savePermissionGroup': 'Save permission group',
        'admin.cidrManagement': 'CIDR management',
        'admin.searchCidr': 'Search CIDR',
        'admin.expirationDateTime': 'Expiration date and time',
        'admin.addCidr': 'Add CIDR',
        'admin.registeredCidrs': 'Registered CIDRs',
        'admin.deleteSelectedCidrsTitle': 'Delete selected CIDR rules?',
        'admin.deleteSelectedCidrsMessage':
          '{count} CIDR rules will be removed from this group.',
        'admin.deleteSelectedCidrsConfirm': 'Delete selected CIDRs',
        'admin.selectCidr': 'Select {cidr}',
        'admin.remove': 'Remove',
        'admin.emptyCidrSearch': 'No CIDR rules found.',
        'admin.emptyRegisteredCidrs': 'No CIDR rules registered.',
        'admin.cidrManagementPage': 'CIDR management page',
        'admin.groupUsers': 'Group users',
        'admin.searchCurrentMembers': 'Search current members',
        'admin.searchMembers': 'Search members',
        'admin.searchUsersToAdd': 'Search users to add',
        'admin.searchUsers': 'Search users',
        'admin.currentMembers': 'Current members',
        'admin.selectedUsersCount': '{count} selected',
        'admin.deleteSelectedUsersTitle':
          'Remove selected users from the group?',
        'admin.deleteSelectedUsersMessage':
          '{count} users will be removed from this group.',
        'admin.deleteSelectedUsersConfirm': 'Remove selected users',
        'admin.selectUser': 'Select {name}',
        'admin.emptyGroupMembers': 'No users are in this group.',
        'admin.groupMemberPage': 'Group member page',
        'admin.add': 'Add',
        'admin.cancel': 'Cancel',
        'admin.addUserToGroup': 'Add user to group',
        'admin.addUserToGroupDescription':
          'Add {name} to this permission group.',
        'admin.assignmentReason': 'Reason',
        'admin.assignmentReasonPlaceholder':
          'Why this permission group is being applied to the user',
        'admin.assignmentReasonPublicCheckbox':
          'Show this reason to the user and API responses',
        'admin.assignmentReasonPublic': 'Reason public',
        'admin.assignmentReasonPrivate': 'Reason private',
        'admin.emptyAddableUsers': 'No users can be added.',
        'admin.searchUsersByNameEmailId': 'Search users by name, email, or ID.',
        'admin.addableUsersPage': 'Users to add page',
        'admin.deleteGroup': 'Delete group',
        'admin.deleteGroupTitle': 'Delete this permission group?',
        'admin.deleteGroupMessage':
          'All permission overrides configured for this group will be removed.',
        'admin.itemNotFound': 'Admin item not found.',
        'admin.noExpiration': 'No expiration',
        'admin.expirationDateError': 'Invalid expiration date',
        'admin.expiredAt': 'Expired {value}',
        'admin.expiresAt': 'Expires {value}',
        'server.adminUserRequiresRoot':
          'Only root administrators can create or edit administrator users.',
        'server.adminUserManageRequiresRoot':
          'Only root administrators can manage administrator users.',
        'server.manageUsersDenied':
          'You do not have permission to manage users.',
        'server.permissionActionDenied':
          'You do not have permission to perform this permission management action.',
        'server.userCreated': 'User added.',
        'server.groupCreated': 'Permission group added.',
        'server.selectGroupsToDelete': 'Select permission groups to delete.',
        'server.groupsDeleted': 'Deleted {count} permission groups.',
        'server.unsupportedPluginAction': 'Unsupported plugin action.',
        'server.userNotFound': 'User not found.',
        'server.groupNotFound': 'Permission group not found.',
        'server.invalidAdminItem': 'Invalid admin item.',
        'server.userSaved': 'User information saved.',
        'server.userDeleted': 'User deleted.',
        'server.groupSaved': 'Permission group saved.',
        'server.groupUserAdded': 'User added to the group.',
        'server.groupUserRemoved': 'User removed from the group.',
        'server.selectUsersToRemove': 'Select users to remove.',
        'server.usersRemoved': 'Removed {count} users from the group.',
        'server.groupCidrAdded': 'CIDR rule added to the group.',
        'server.groupCidrRemoved': 'CIDR rule removed from the group.',
        'server.selectCidrsToRemove': 'Select CIDR rules to remove.',
        'server.cidrsRemoved': 'Removed {count} CIDR rules from the group.',
        'server.groupDeleted': 'Permission group deleted.',
        'server.apiTokenNotFound': 'API token not found.',
        'server.apiTokenRevoked': 'API token revoked.',
        'server.unsupportedPermissionAction':
          'Unsupported permission management action.',
      },
    },
  },
  defaultConfig: {},
  parseConfig(_form, current) {
    return current;
  },
};

export default plugin;
